#!/usr/bin/env ruby

git_bundles = []
git_bundles.push "git://github.com/flazz/vim-colorschemes.git"
git_bundles.push "git://github.com/scrooloose/nerdtree.git"
#git_bundles.push "git://github.com/fatih/vim-go.git"
#git_bundles.push "git://github.com/ecomba/vim-ruby-refactoring.git"
#git_bundles.push "git://github.com/godlygeek/tabular.git"
#git_bundles.push "git://github.com/groenewege/vim-less.git"
#git_bundles.push "git://github.com/elzr/vim-json.git"
#git_bundles.push "git://github.com/jgdavey/vim-blockle.git"
#git_bundles.push "git://github.com/kana/vim-textobj-user.git"
#git_bundles.push "git://github.com/kchmck/vim-coffee-script.git"
#git_bundles.push "git://github.com/kien/ctrlp.vim.git"
#git_bundles.push "git://github.com/nelstrom/vim-textobj-rubyblock.git"
#git_bundles.push "git://github.com/pangloss/vim-javascript.git"
#git_bundles.push "git://github.com/sickill/vim-pasta.git"
#git_bundles.push "git://github.com/timcharper/textile.vim.git"
#git_bundles.push "git://github.com/tomtom/tcomment_vim.git"
#git_bundles.push "git://github.com/tpope/vim-cucumber.git"
#git_bundles.push "git://github.com/tpope/vim-endwise.git"
#git_bundles.push "git://github.com/tpope/vim-fugitive.git"
#git_bundles.push "git://github.com/tpope/vim-git.git"
#git_bundles.push "git://github.com/tpope/vim-haml.git"
#git_bundles.push "git://github.com/tpope/vim-markdown.git"
#git_bundles.push "git://github.com/tpope/vim-rails.git"
#git_bundles.push "git://github.com/tpope/vim-repeat.git"
#git_bundles.push "git://github.com/tpope/vim-surround.git"
#git_bundles.push "git://github.com/tpope/vim-vividchalk.git"
#git_bundles.push "git://github.com/tsaleh/vim-matchit.git"
#git_bundles.push "git://github.com/tsaleh/vim-shoulda.git"
#git_bundles.push "git://github.com/tsaleh/vim-tmux.git"
#git_bundles.push "git://github.com/vim-ruby/vim-ruby.git"
#git_bundles.push "git://github.com/vim-scripts/Gist.vim.git"
#git_bundles.push "git://github.com/vim-scripts/IndexedSearch.git"
#git_bundles.push "git://github.com/vim-scripts/jQuery.git"
#git_bundles.push "git://github.com/Lokaltog/vim-powerline.git"
#git_bundles.push "git://github.com/slim-template/vim-slim.git"

require 'fileutils'
require 'open-uri'

# Get latest pathogen
base_dir=File.expand_path(File.dirname(__FILE__))
autoload_dir=File.join(base_dir, "autoload")
FileUtils.rm_rf(autoload_dir)
FileUtils.mkdir(autoload_dir)
FileUtils.cd(autoload_dir)
`wget https://raw.githubusercontent.com/tpope/vim-pathogen/v2.3/autoload/pathogen.vim`

bundles_dir = File.join(base_dir, "bundle")
FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }
